repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint *.py handlers/*.py components/*.py
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run pytest -q
        language: system
        pass_filenames: false
